
name: Build Android

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platform-tools platforms;android-35 build-tools;35.0.0'

      - name: Build Release APK
        run: |
          cd tools/android_project/
          chmod +x gradlew
          ./gradlew assembleRelease
          ls -lah app/build/outputs/apk/release/

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidRelease
          path: tools/android_project/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
          retention-days: 14
